[options]
nodeVersion = "20"

[aptPackages]
packages = [
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2",
  "libpango-1.0-0",
  "libcairo2",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libxkbcommon0",
  "libdrm2"
]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx playwright install chromium"]
